name: Test
on:
  pull_request:
    branches:
    - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Install dependencies
        run: npm install
      - name: Check tests
        run: npm test

